-- 1. Create Customers Table
CREATE TABLE customers (
    customer_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cust_name     VARCHAR2(100),
    segment       VARCHAR2(20) DEFAULT 'BRONZE', -- Bronze, Silver, Gold
    signup_date   DATE
);

-- 2. Create Products Table
CREATE TABLE products (
    product_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name  VARCHAR2(100),
    category      VARCHAR2(50),
    unit_price    NUMBER(10, 2)
);

-- 3. Create Transactions Table (The Fact Table)
CREATE TABLE sales_transactions (
    txn_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   NUMBER,
    product_id    NUMBER,
    quantity      NUMBER,
    txn_date      DATE,
    CONSTRAINT fk_cust FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    CONSTRAINT fk_prod FOREIGN KEY (product_id) REFERENCES products(product_id)
);